services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - db
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .env:/backend/.env
      - ./backend:/backend
    environment:
      PYTHONPATH: app
      POSTGRES_HOST: db
      # Application settings below
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD_ESCAPED}@db:5432/${POSTGRES_DB}
      LOG_LEVEL: ${LOG_LEVEL}
    ports:
      - "8000:8000"
    networks:
      - app_network

  frontend:
    build:
      context: frontend
      target: dev
    depends_on:
      - backend
    restart: always
    command: npm run dev
    volumes:
      - .env:/frontend/.env
      - ./frontend:/frontend
      - /frontend/node_modules # This is to avoid rebuilding the node_modules
    environment:
      - BACKEND_URL=http://backend:8000
      - NODE_ENV=development # This is to avoid building the app in production mode
    ports:
      - "3000:3000"
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
