services: 
  frontend:
    build: 
      context: frontend
      target: prod
    restart: always #change if you don't want your container restarting
    environment:
      - BACKEND_URL=http://backend:8000
      - NODE_ENV=production
    ports:
      - 3000:3000
    networks:
      - app_network